# type: ignore

"""Initialisation

Revision ID: 3136035df46a
Revises: 
Create Date: 2023-10-28 22:20:01.609584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3136035df46a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code',
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('value')
    )
    op.create_table('bind',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['code'], ['code.value'], ),
    sa.PrimaryKeyConstraint('code', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bind')
    op.drop_table('code')
    # ### end Alembic commands ###
