services:
  digidive:
    build:
      dockerfile: ./Dockerfile
      target: debug
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app
        - action: rebuild
          path: ./uv.lock
    restart: "no"
    ports:
      - 80:8000
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    tty: true
    init: true
