version: "3.8"

services:
  digidive:
    env_file:
      - .env
    build:
      context: .
      target: prod
    ports:
      - 80:8000
    expose:
      - 8000
    restart: unless-stopped
    volumes:
      - ./data:/app/data
